package com.openlakehouse.lineage.driver

/**
 * In-memory model of the OpenLineage 1-2-0 `ColumnLineageDatasetFacet`.
 *
 * The corresponding wire types live in `lineage.v1.Lineage.ColumnLineageDatasetFacet`
 * (generated by buf). Keeping a Scala-native model here lets the extractor stay
 * decoupled from generated Java types — `ColumnLineageEncoder` is the only
 * place that bridges the two.
 *
 * Identity / equality is structural: two facets with the same fields and
 * dataset deps compare equal, which keeps tests and dedup logic simple.
 */
final case class ColumnLineageFacet(
    fields: Map[String, Seq[ColumnLineageInputField]],
    dataset: Seq[ColumnLineageInputField]
) {
  def isEmpty: Boolean  = fields.isEmpty && dataset.isEmpty
  def nonEmpty: Boolean = !isEmpty
}

object ColumnLineageFacet {
  val Empty: ColumnLineageFacet = ColumnLineageFacet(Map.empty, Seq.empty)
}

/**
 * Single column-level dependency on a source dataset's field.
 *
 * The `transformations` array records *how* the input feeds the output: a
 * column read straight through is `DIRECT/IDENTITY`; a column passed through
 * a hash is `DIRECT/TRANSFORMATION` with `masking=true`; a column referenced
 * by a join condition is `INDIRECT/JOIN`.
 */
final case class ColumnLineageInputField(
    namespace: String,
    name: String,
    field: String,
    transformations: Seq[ColumnLineageTransformation] = Seq.empty
) {
  /** Identity used to merge transformation lists across plan paths. */
  def identity: (String, String, String) = (namespace, name, field)
}

/**
 * Describes one way an input field feeds an output column.
 *
 * `kind` is the OpenLineage `type` field (`DIRECT` or `INDIRECT`); we use
 * `kind` here because `type` is reserved in Scala. `subtype` further
 * qualifies it (`IDENTITY`, `TRANSFORMATION`, `AGGREGATION`, `JOIN`,
 * `GROUP_BY`, `FILTER`, `SORT`, `WINDOW`, `CONDITIONAL`).
 *
 * `description` is a free-form expression label (typically the SQL function
 * name for transformations / aggregations, or empty for IDENTITY).
 *
 * `masking` is set when the transformation removes signal from the input
 * (hashes, redactions, intentional noise).
 */
final case class ColumnLineageTransformation(
    kind: String,
    subtype: String,
    description: String = "",
    masking: Boolean = false
)

object ColumnLineageTransformation {
  val DirectKind: String   = "DIRECT"
  val IndirectKind: String = "INDIRECT"

  val Identity: ColumnLineageTransformation       = ColumnLineageTransformation(DirectKind, "IDENTITY")
  def transformation(desc: String, masking: Boolean = false): ColumnLineageTransformation =
    ColumnLineageTransformation(DirectKind, "TRANSFORMATION", desc, masking)
  def aggregation(desc: String): ColumnLineageTransformation =
    ColumnLineageTransformation(DirectKind, "AGGREGATION", desc)

  def indirect(subtype: String, desc: String = ""): ColumnLineageTransformation =
    ColumnLineageTransformation(IndirectKind, subtype, desc)

  val Filter: ColumnLineageTransformation = indirect("FILTER")
  val Sort: ColumnLineageTransformation   = indirect("SORT")
  val Join: ColumnLineageTransformation   = indirect("JOIN")
  val GroupBy: ColumnLineageTransformation = indirect("GROUP_BY")
  val Window: ColumnLineageTransformation = indirect("WINDOW")
}

/**
 * Helpers for merging `ColumnLineageInputField`s as we propagate them up the
 * plan. Inputs are deduplicated by `(namespace, name, field)`; transformation
 * lists are unioned (preserving first-seen order) so callers can see every
 * way an input contributed without paying for duplicate entries.
 */
private[driver] object ColumnLineageInputField {

  /** Union two input field sequences, merging transformations on identity. */
  def merge(
      a: Seq[ColumnLineageInputField],
      b: Seq[ColumnLineageInputField]
  ): Seq[ColumnLineageInputField] = mergeAll(Seq(a, b))

  /** Like `merge`, but variadic. */
  def mergeAll(seqs: Seq[Seq[ColumnLineageInputField]]): Seq[ColumnLineageInputField] = {
    val out   = scala.collection.mutable.LinkedHashMap.empty[(String, String, String), ColumnLineageInputField]
    seqs.foreach { seq =>
      seq.foreach { field =>
        out.get(field.identity) match {
          case Some(existing) =>
            val merged = existing.copy(
              transformations = unionTransformations(existing.transformations, field.transformations)
            )
            out.update(field.identity, merged)
          case None =>
            out.update(field.identity, field)
        }
      }
    }
    out.values.toVector
  }

  /** Attach an extra transformation to every input in `seq`, in-place semantics. */
  def withTransformation(
      seq: Seq[ColumnLineageInputField],
      t: ColumnLineageTransformation
  ): Seq[ColumnLineageInputField] = seq.map { f =>
    f.copy(transformations = unionTransformations(f.transformations, Seq(t)))
  }

  private def unionTransformations(
      a: Seq[ColumnLineageTransformation],
      b: Seq[ColumnLineageTransformation]
  ): Seq[ColumnLineageTransformation] = {
    val seen = scala.collection.mutable.LinkedHashSet.empty[ColumnLineageTransformation]
    a.foreach(seen.add)
    b.foreach(seen.add)
    seen.toVector
  }
}
